name: test
on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out this project
        uses: actions/checkout@v2
      - name: Test
        run: |
          echo "GH ACTOR: " "$GITHUB_ACTOR"
          git config --list
          git config user.email || echo "failed"
      - name: Var test
        run: |
          VAR=true
          echo "(env)     VAR=$VAR"
          echo "(context) VAR=${{ env.VAR }}"
