name: test
on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out this project
        uses: actions/checkout@v2
      - name: Install ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
      - name: Run compare
        run: |
          set +x
          compare tall.png tall.png NULL: || echo '(failed 1)'
          compare -metric RMSE tall.png tall.png NULL: || echo '(failed 2)'
